prune:
  checkpoint_name: checkpoint_final.pth
  fold:
  - - 0
  - - 1
  - - 2
  - - 3
  - - 4
  - - all
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  model_folder: nnUNet_results_norm_off/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  output_folder: /media/tonguyunyang/tony_data/data/pruning_nnunet_experiment_storage/prune_predictions_norm_off_bottleneck
  prune_method: RangePruning
  prune_parameters:
    max_val: 0
    min_val: 0
    prune_bias: true
    prune_layers:
    - encoder.stages.5.0.convs.0.conv
    - encoder.stages.5.0.convs.1.conv
    - decoder.transpconvs.0
    - decoder.transpconvs.1
    - decoder.transpconvs.2
    - decoder.transpconvs.3
    prune_weights: true
