prune:
  checkpoint_name: checkpoint_final.pth
  fold:
  - - 0
  - - 1
  - - 2
  model_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  gt_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  prune_method: RangePruning
  prune_parameters:
    max_val: 0.001
    min_val: -0.001
    prune_bias: true
#    layers:
  output_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d/prune_predictions
