prune:
  checkpoint_name: checkpoint_final.pth
  fold:
  - - 0
  - - 1
  - - 2
  - - 3
  - - 4
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  model_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  output_folder: /media/tonguyunyang/tony_data/data/pruning_nnunet_experiment_storage/prune_predictions
  prune_method: RangePruning
  prune_parameters:
    max_val: 0
    min_val: 0
    prune_bias: true
    prune_layers:
    - norm
    - conv
    prune_weights: true
