prune:
  checkpoint_name: checkpoint_final.pth
  fold:
  - - all
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  model_folder: nnUNet_results_norm_off_bottleneck_up_1/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  output_folder: /media/tonguyunyang/tony_data/data/pruning_nnunet_experiment_storage/prune_predictions_norm_off_bottleneck_up_1
  prune_method: FlowPruning
  prune_parameters:
    eliminate_data_flow: encoder
    prune_layers:
    - decoder.stages.0.convs.0.conv
    - decoder.stages.1.convs.0.conv
    - decoder.stages.2.convs.0.conv
    prune_weights: true
