prune:
  return_intermediates: true
  checkpoint_name: checkpoint_final.pth
  fold:
  - - 0
    - 1
    - 2
    - 3
    - 4
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  model_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  output_folder: /media/tonguyunyang/tony_data/data/pruning_nnunet_experiment_storage/test
  prune_method: RangePruning
  prune_parameters:
    max_val: 0.1
    min_val: -0.1
    prune_bias: true
    prune_layers:
    - decoder.stages.0.convs.0.conv
    - decoder.stages.1.convs.0.conv
    - decoder.stages.2.convs.0.conv
    prune_weights: true
