prune:
  model_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d  # Path to the trained model folder, the folder that includes subdirs of fold_X
  fold: [0, 1, 2] # Please only put single integers here
  checkpoint_name: checkpoint_final.pth
  prune_method: RangePruning
  prune_parameters:
    max_val: 0.001
    min_val: -0.001
    prune_bias: true

  # Prediction folder after pruning
  predict:
    input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
    # output_folder: nnUNet_results_prune_test/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d/predictions_test2  # Output folder to save predictions