evaluate:
  chill: false
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  num_processes: 8
  output_file: null
  pruned: true
plot:
  base_dir: nnUNet_results
  checkpoint_name: checkpoint_final.pth
  dataset_id: 27
  folds:
  - 0
  - 1
  - 2
  - 3
  - 4
  model_version: FlexibleTrainerV1__nnUNetPlans__2d
  output_dir: parameter_distributions
predict:
  checkpoint_name: checkpoint_best.pth
  continue_prediction: false
  device: cuda
  disable_progress_bar: false
  disable_tta: false
  fold:
  - 0
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  num_processes_preprocessing: 3
  num_processes_segmentation_export: 3
  output_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d/predictions
  save_probabilities: false
  step_size: 0.5
  verbose: true
prune:
  checkpoint_name: checkpoint_final.pth
  fold: 4
  model_folder: nnUNet_results_prune_test/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d
  predict:
    input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
    output_folder: nnUNet_results_prune_test/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d/predictions/fold_4/final_model/RangePruning__0e+__0e+__no_bias
  prune_method: RangePruning
  prune_parameters:
    max_val: 0.0
    min_val: 0.0
    prune_bias: false
train:
  c: false
  configuration: 2d
  dataset_name_or_id: 27
  device: cuda
  fold:
  - all
  npz: false
  num_gpus: 1
  p: nnUNetPlans
  pretrained_weights: null
  tr: FlexibleTrainerV1
  val: false
  val_best: false
