# Required parameters
dataset_name_or_id: 27  # Dataset name or ID to train with
configuration: 2d # 2d, 3d_fullres, 3d_lowres, 3d_cascade_fullres
fold: [0, 1, 2]  # Fold(s) of the 5-fold cross-validation (integers between 0 and 4)

# Optional parameters with default values
tr: FlexibleTrainerV1  # Custom trainer (default: nnUNetTrainer)
p: nnUNetPlans  # Custom plans identifier (default: nnUNetPlans)
pretrained_weights: null  # Path to nnU-Net checkpoint file for pretrained model
num_gpus: 1  # Number of GPUs to use for training
device: cuda  # Device to run on (cuda, cpu, mps)

# Boolean flags
npz: false  # Save softmax predictions as npz files
c: false  # Continue training from latest checkpoint
val: false  # Only run validation (requires training to have finished)
val_best: false  # Use checkpoint_best for validation
disable_checkpointing: false  # Disable checkpointing