evaluate:
  checkpoint_name: null
  chill: false
  gt_folder: nnUNet_raw/Dataset027_ACDC/labelsTs
  num_processes: 8
  output_file: null
  pred_folder: null
  pruned: true
  result_base_dir: null
plot:
  alpha: 0.7
  analysis:
    component_wise: true
    layer_wise: true
    stage_wise: true
  base_dir: nnUNet_results
  bins: 50
  checkpoint_name: checkpoint_final.pth
  colors:
    fit: '#ff0000'
    init: '#ff7f0e'
    trained: '#1f77b4'
  components:
  - encoder
  - decoder
  dataset_name_or_id: 27
  dpi: 300
  figsize:
    height: 4
    width: 15
  fold:
  - 0
  - 1
  - 2
  - 3
  - 4
  max_cols: 4
  output_dir: weight_distribution
  show_kurtosis: true
  show_theoretical: true
  textbox_alpha: 0.3
  trainer_plan_version: FlexibleTrainerV1__nnUNetPlans__2d
predict:
  checkpoint_name: checkpoint_final.pth
  continue_prediction: false
  device: cuda
  disable_progress_bar: false
  disable_tta: false
  fold:
  - - 0
    - 1
    - 2
    - 3
    - 4
  input_folder: nnUNet_raw/Dataset027_ACDC/imagesTs
  num_processes_preprocessing: 3
  num_processes_segmentation_export: 3
  output_folder: nnUNet_results/Dataset027_ACDC/FlexibleTrainerV1__nnUNetPlans__2d/predictions
  return_intermediates: true
  save_probabilities: false
  step_size: 0.5
  verbose: true
train:
  bottleneck_removal_layers: null
  c: false
  configuration: 2d
  dataset_name_or_id: 27
  device: cuda
  fold:
  - 0
  - 1
  - 2
  - 3
  - 4
  npz: false
  num_gpus: 1
  p: nnUNetPlans
  pretrained_weights: null
  tr: FlexibleTrainerV1
  val: false
  val_best: false
